# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: npm install and npm run build
        run: |
          npm i
          ng build --prod
          ls ./dist

      - name: Angular Deploy gh-pages Actions
        # You may pin to the exact commit or the version.
        # uses: AhsanAyaz/angular-deploy-gh-pages-actions@0e4f1a953d00116ca38fbf1bcdb37f91923015ef
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          # Github access token token used to deploy on gh_pages. You can find it on Github.
          #github_access_token: 
          # The directory of the angular project, in which all the commands will run
          angular_project_dir: ./
          # Build configuration for the angular app
          build_configuration: production
          # base href for the app
          base_href: /percepcao-de-espacos-publicos/
          # branch on which the angular build will be deployed
          deploy_branch: gh-pages
          # The folder in which `ng build` provides its output. This is the folder which will be deployed to the `deploy_branch`.
          angular_dist_build_folder: dist
          # If the action should run 'ng lint'
          run_lint: true
          # Will not fail the step if anything fails
          skip_failure: false
          

